![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [1]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.21.5


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [14]:
# your code goes here
np.array([0.]*10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
#np.array([0] * 10)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with values ranging from 10 to 49

In [26]:
# your code goes here
l = []
for i in range(10,50):
    l.append(i)
np.array(l)
    

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [27]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 2*2 integers, filled with ones.

In [62]:
# your code goes here
l = []
m = []
n = [l,m]
integer = 1
for i in range(1,3):
    l.append(interger)
    m.append(interger)
np.array(n)

array([[1, 1],
       [1, 1]])

In [63]:
np.ones([2,2], dtype=np.int)

/var/folders/gq/qw2m5gmj4l38c512z3nt41h80000gp/T/ipykernel_50685/2225746612.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([2,2], dtype=np.int)


array([[1, 1],
       [1, 1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [67]:
# your code goes here
# your code goes here
l, m, n = [], [], []
o = [l,m,n]
integer = 1
for i in range(1,3):
    l.append(interger)
    m.append(interger)
    n.append(interger)
np.array(o, dtype=np.float)

/var/folders/gq/qw2m5gmj4l38c512z3nt41h80000gp/T/ipykernel_50685/2383378240.py:10: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array(o, dtype=np.float)


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [65]:
np.ones([3,2], dtype=np.float)

/var/folders/gq/qw2m5gmj4l38c512z3nt41h80000gp/T/ipykernel_50685/2134205708.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([3,2], dtype=np.float)


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [ ]:
# your code goes here


In [70]:
X = np.arange(4, dtype=np.int)

np.ones_like(X)

/var/folders/gq/qw2m5gmj4l38c512z3nt41h80000gp/T/ipykernel_50685/2717597073.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.arange(4, dtype=np.int)


array([1, 1, 1, 1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [71]:
# your code goes here
X = np.array([[5,6,7,8], [8,9,10,11], [12,13,14,15]], dtype=np.float)

np.zeros_like(X)

/var/folders/gq/qw2m5gmj4l38c512z3nt41h80000gp/T/ipykernel_50685/3904243837.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.array([[5,6,7,8], [8,9,10,11], [12,13,14,15]], dtype=np.float)


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int)

np.zeros_like(X)

/var/folders/gq/qw2m5gmj4l38c512z3nt41h80000gp/T/ipykernel_50685/3272494631.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.array([[1,2,3], [4,5,6]], dtype=np.int)


array([[0, 0, 0],
       [0, 0, 0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 4*4 integers, filled with fives.

In [76]:
# your code goes here
np.ones([4,4], dtype=np.int) * 5

/var/folders/gq/qw2m5gmj4l38c512z3nt41h80000gp/T/ipykernel_50685/3106978584.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([4,4], dtype=np.int) * 5


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [73]:
np.ones([4,4], dtype=np.int) * 5

/var/folders/gq/qw2m5gmj4l38c512z3nt41h80000gp/T/ipykernel_50685/3878826747.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([4,4], dtype=np.int) * 5


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [79]:
# your code goes here
X = np.array([[5,6], [7,8]], dtype=np.int)

np.ones_like(X) * 7

/var/folders/gq/qw2m5gmj4l38c512z3nt41h80000gp/T/ipykernel_50685/2755891861.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.array([[5,6], [7,8]], dtype=np.int)


array([[7, 7],
       [7, 7]])

In [80]:
X = np.array([[2,3], [6,2]], dtype=np.int)

np.ones_like(X) * 7

/var/folders/gq/qw2m5gmj4l38c512z3nt41h80000gp/T/ipykernel_50685/148286267.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.array([[2,3], [6,2]], dtype=np.int)


array([[7, 7],
       [7, 7]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [93]:
# your code goes here
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#np.eye(3)
np.identity(3)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [94]:
# your code goes here
np.random.randint(10, size=3)

array([4, 8, 9])

In [95]:
np.random.randint(10, size=3)

array([9, 5, 7])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3\*3\*3 numpy matrix, filled with random float values.

In [96]:
# your code goes here
np.random.randn(3,3,3)

array([[[ 1.25325428,  1.49829035, -1.64462246],
        [-1.71136844, -0.00442071,  1.95032872],
        [-0.50846964,  2.02007919,  1.13060821]],

       [[-1.93700186, -0.02834652, -0.35648818],
        [ 0.65090101, -0.75408606, -1.05901769],
        [ 0.17470225,  0.64916415, -1.08022808]],

       [[-0.27532951,  0.0779313 ,  0.61865578],
        [ 0.25266392,  1.64734576,  0.07132176],
        [ 0.92115365, -2.63749632,  0.49936246]]])

In [97]:
#np.random.random((3,3,3)) 
np.random.randn(3,3,3) # 0 to 1 floats

array([[[ 0.27217576, -0.06857404, -0.18322968],
        [-1.65116179,  1.37964473,  0.78138047],
        [ 0.14759515, -2.2319424 ,  0.14947291]],

       [[-1.03083136, -0.61537092, -0.58434866],
        [ 1.13779467, -1.03569484, -1.25377057],
        [-1.86340027, -0.4716809 ,  0.18715081]],

       [[ 0.69524128, -2.56868789, -0.28150765],
        [ 1.52368206,  0.29010079,  1.10314017],
        [ 1.91377715,  1.11497687,  2.16922482]]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y numpy array

In [101]:
# your code goes here
X = [2, 3, 4]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y))

[2, 3, 4] <class 'list'>
[2 3 4] <class 'numpy.ndarray'>


In [102]:
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y)) # different type

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, make a copy and store it on Y.

In [105]:
# your code goes here
X = np.array([4,5,6], dtype=np.int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y))

[4 5 6] 140457029370480
[4 5 6] 140457030327056


/var/folders/gq/qw2m5gmj4l38c512z3nt41h80000gp/T/ipykernel_50685/1144938840.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.array([4,5,6], dtype=np.int)


In [106]:
X = np.array([5,2,3], dtype=np.int)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

[5 2 3] 140457030406032
[5 2 3] 140457030327344


/var/folders/gq/qw2m5gmj4l38c512z3nt41h80000gp/T/ipykernel_50685/1638623950.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X = np.array([5,2,3], dtype=np.int)


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10

In [107]:
# your code goes here
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [108]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with the odd numbers between 1 to 10

In [111]:
# your code goes here
np.arange(1, 11, 3)

array([ 1,  4,  7, 10])

In [ ]:
np.arange(1, 11, 2)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10, in descending order.

In [125]:
# your code goes here
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [126]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [131]:
# your code goes here
np.arange(0, 9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [132]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Show the memory size of the given Z numpy matrix

In [134]:
# your code goes here
Z = np.ones((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [135]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [136]:
# your code goes here
X = np.array([1,2,3])
X[0]

1

In [137]:
X = np.array(['A','B','C','D','E'])

X[0]

'A'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's last element

In [139]:
# your code goes here
X = np.array([1,2,3,4])
X[-1]

4

In [140]:
X = np.array(['A','B','C','D','E'])

#X[len(X)-1]
X[-1]

'E'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's first three elements

In [146]:
# your code goes here
X = np.array(['1','2','3'])

X[0:3]

array(['1', '2', '3'], dtype='<U1')

In [147]:
X = np.array(['A','B','C','D','E'])

X[0:3] # remember! elements start at zero index

array(['A', 'B', 'C'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show all middle elements

In [160]:
# your code goes here
X = np.array(["2","5","3","6","7"])
X[1:-1]

array(['5', '3', '6'], dtype='<U1')

In [154]:
X = np.array(['A','B','C','D','E'])

X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in reverse position

In [168]:
# your code goes here
X = np.array(["A","B","C","D"])
X[::-1]

array(['D', 'C', 'B', 'A'], dtype='<U1')

In [169]:
X = np.array(['A','B','C','D','E'])

X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in an odd position

In [175]:
# your code goes here
X = np.array(['A', 'B', 'C', 'D', 'E'])
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

In [176]:
X = np.array(['A','B','C','D','E'])

#X[[0, 2, -1]]
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first row elements

In [182]:
# your code goes here
X =np.array([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12] 
            ])
X[0]

array([1, 2, 3, 4])

In [183]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last row elements

In [185]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[-1]

array([13, 14, 15, 16])

In [186]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]

array([13, 14, 15, 16])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first element on first row

In [187]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[0][0]

1

In [188]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[0][0]
X[0, 0]

1

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last element on last row

In [189]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[-1][-1]

16

In [190]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[-1][-1]
X[-1, -1]

16

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the middle row elements

In [198]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[1:-1]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [199]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[1:-1][1:-1] wrong!
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first two elements on the first two rows

In [204]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[:2, :2]

array([[1, 2],
       [5, 6]])

In [205]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[:2][:2] wrong!
#X[0:2, 0:2]
X[:2, :2]

array([[1, 2],
       [5, 6]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last two elements on the last two rows

In [218]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[2:, 2:]

array([[11, 12],
       [15, 16]])

In [217]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:, 2:]

array([[11, 12],
       [15, 16]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [219]:
# your code goes here
X = [-5, -3, 0, 10, 40]
np.array(X, np.float)

/var/folders/gq/qw2m5gmj4l38c512z3nt41h80000gp/T/ipykernel_50685/4265410497.py:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array(X, np.float)


array([-5., -3.,  0., 10., 40.])

In [220]:
X = [-5, -3, 0, 10, 40]

np.array(X, np.float)

/var/folders/gq/qw2m5gmj4l38c512z3nt41h80000gp/T/ipykernel_50685/4247539020.py:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array(X, np.float)


array([-5., -3.,  0., 10., 40.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given numpy array (first element becomes last)

In [221]:
# your code goes here
X = [-5, -3, 0, 10, 40]
X[::-1]

[40, 10, 0, -3, -5]

In [222]:
X = [-5, -3, 0, 10, 40]

X[::-1]

[40, 10, 0, -3, -5]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given numpy array

In [225]:
# your code goes here
X = [-5, -3, 0, 10, 40]
X.sort()
X

[-5, -3, 0, 10, 40]

In [226]:
X = [0, 10, -5, 40, -3]

X.sort()
X

[-5, -3, 0, 10, 40]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, set the fifth element equal to 1

In [238]:
# your code goes here
X = np.arange(2, 10)
X[4] = 1
X

array([2, 3, 4, 5, 1, 7, 8, 9])

In [240]:
X = np.zeros(10)

X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, change the 50 with a 40

In [249]:
X = np.array([10, 20, 30, 50])

X[3] = 40
X

array([10, 20, 30, 40])

In [250]:
X = np.array([10, 20, 30, 50])

X[3] = 40
X

array([10, 20, 30, 40])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last row with all 1

In [256]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[-1] = [1, 1, 1, 1]
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [257]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1, 1, 1, 1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last item on the last row with a 0

In [259]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

In [260]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, add 5 to every element

In [261]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [262]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

In [264]:
# your code goes here
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [265]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get the negative elements

In [269]:
# your code goes here
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
mask = X <= 0
X[mask]

array([-1,  0, -4,  0,  0, -9])

In [270]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X <= 0
X[mask]

array([-1,  0, -4,  0,  0, -9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than 5

In [271]:
# your code goes here
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]


array([ 6, 10])

In [272]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

array([ 6, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than the elements mean

In [275]:
# your code goes here
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])

In [276]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers equal to 2 or 10

In [281]:
# your code goes here
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

In [282]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


### Given the X numpy array, return True if none of its elements is zero

In [284]:
# your code goes here
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X.all()

False

In [285]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

False

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, return True if any of its elements is zero

In [286]:
# your code goes here
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

True

In [287]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

True

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X numpy array, show the sum of its elements

In [290]:
# your code goes here
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

#np.sum(X)
X.sum()

43

In [ ]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

#np.sum(X)
X.sum()

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the mean value of its elements

In [291]:
# your code goes here
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.mean(X)
X.mean()

3.7

In [ ]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.mean(X)
X.mean()

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the sum of its columns

In [302]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0) # remember: axis=0 columns; axis=1 rows

array([28, 32, 36, 40])

In [303]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0) # remember: axis=0 columns; axis=1 rows

array([28, 32, 36, 40])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the mean value of its rows

In [304]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1) # remember: axis=0 columns; axis=1 rows

array([ 2.5,  6.5, 10.5, 14.5])

In [ ]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1) # remember: axis=0 columns; axis=1 rows

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the max value of its elements

In [308]:
# your code goes here
X = np.array([1,3,4,56])
X.max()

56

In [312]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.max(X)
X.max()

10

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)